In [44]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree

In [45]:
df = pd.read_csv('./unbalanced.csv')
df.head()

,id,WBN_GC_L_0.25,WBN_GC_H_0.25,WBN_GC_L_0.50,WBN_GC_H_0.50,WBN_GC_L_0.75,WBN_GC_H_0.75,WBN_GC_L_1.00,WBN_GC_H_1.00,WBN_EN_L_0.25,...,WBN_LP_H_1.00,XLogP,PSA,NumRot,NumHBA,NumHBD,MW,BBB,BadGroup,Outcome
0,1,-2.3941,1.8819,-2.5208,2.3536,-2.7698,3.1048,-3.4568,3.9734,-0.8412,...,3.8086,4.924,60.45,6,4,1,362.857,1,0,Active
1,2,-2.3342,2.3811,-2.6012,2.7420,-3.0632,3.4052,-3.7360,4.2833,-0.8664,...,3.9886,4.954,50.44,2,2,1,320.266,1,0,Active
2,3,-1.4709,2.0782,-1.8538,2.4877,-2.4116,3.0664,-3.1338,3.8454,-0.7940,...,3.6222,1.399,103.22,3,6,1,376.459,0,1,Active
3,4,-1.4722,1.9812,-1.7911,2.3885,-2.4193,2.9938,-3.2212,3.8043,-0.8036,...,3.7461,4.721,137.73,7,6,3,442.581,0,0,Active
4,5,-2.2448,1.9814,-2.3705,2.3951,-2.6219,3.0475,-3.1991,3.8418,-0.7988,...,3.7151,3.912,120.94,7,6,2,401.484,0,0,Active

In [46]:
df.replace({'Active': '0', 'Inactive': '1'}, inplace = True, regex = True)

In [47]:
df.head()

,id,WBN_GC_L_0.25,WBN_GC_H_0.25,WBN_GC_L_0.50,WBN_GC_H_0.50,WBN_GC_L_0.75,WBN_GC_H_0.75,WBN_GC_L_1.00,WBN_GC_H_1.00,WBN_EN_L_0.25,...,WBN_LP_H_1.00,XLogP,PSA,NumRot,NumHBA,NumHBD,MW,BBB,BadGroup,Outcome
0,1,-2.3941,1.8819,-2.5208,2.3536,-2.7698,3.1048,-3.4568,3.9734,-0.8412,...,3.8086,4.924,60.45,6,4,1,362.857,1,0,0
1,2,-2.3342,2.3811,-2.6012,2.7420,-3.0632,3.4052,-3.7360,4.2833,-0.8664,...,3.9886,4.954,50.44,2,2,1,320.266,1,0,0
2,3,-1.4709,2.0782,-1.8538,2.4877,-2.4116,3.0664,-3.1338,3.8454,-0.7940,...,3.6222,1.399,103.22,3,6,1,376.459,0,1,0
3,4,-1.4722,1.9812,-1.7911,2.3885,-2.4193,2.9938,-3.2212,3.8043,-0.8036,...,3.7461,4.721,137.73,7,6,3,442.581,0,0,0
4,5,-2.2448,1.9814,-2.3705,2.3951,-2.6219,3.0475,-3.1991,3.8418,-0.7988,...,3.7151,3.912,120.94,7,6,2,401.484,0,0,0

In [48]:
x = df.values[:, 1:33]
y = df.values[:, 33]

In [49]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 100)

In [58]:
clf_entropy = tree.DecisionTreeClassifier(criterion = 'entropy')

In [59]:
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [60]:
yprediction = clf_entropy.predict(X_test)

In [61]:
print('Resultado previsto:\n', yprediction, '\n')
print('Resultado atual:\n', y_test, '\n')
print('PrecisÃ£o do modelo de Ã¡rvore de decisÃ£o ID3 para estes dados: ', accuracy_score(y_test, yprediction)*100)

Resultado previsto:
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '0' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '0' '1']

Resultado atual:
 ['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '0' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1'
 '1' '1' '1' '1' '1']

PrecisÃ£o do modelo de Ã¡rvore de decisÃ£o ID3 para estes dados:  98.0544747081712